### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by TheJaredWilcurt** [saschanaz/flif-wasm#8]
I'm testing out `flif-wasm` on Windows for `node-flif`. I was using a native `flif.exe` file for Windows previously and now that `flif-wasm` has support for Windows system folders, I was looking into switching over.

When I ran `npm test` using `flif.exe` it completes in 0.3 seconds. When I run it using `flif-wasm` it takes 15.1 seconds. Which is considerably slower by comparison.

I don't know how WASM stuff works, but I thought I would report this in case there are optimizations that can be done to get it faster.

**Comment by saschanaz** [comment]
flif-wasm doesn't have any valid npm test, what test sets did you use?

**Comment by saschanaz** [comment]
(Note that WASM should first be compiled to native machine code to run, which may be significant when running very short job. Loading flif-wasm binary takes ~0.5 sec on my machine.)

**Comment by TheJaredWilcurt** [comment]
Sorry, should have made that more clear. I was running my own tests in the node-flif repo.

**Comment by saschanaz** [comment]
Great tests there! Unfortunately it still seems the issue is in WASM itself. Maybe some day Node.js would get a cache system for this kind of delay, I don't know...

**Comment by saschanaz** [comment]
It seems browsers already supports caching by IndexedDB API (which now supports `WebAssembly.Module`), not sure Node.js has an equivalent wasm caching mechanism.

**Comment by TheJaredWilcurt** [comment]
@saschanaz 

I've created a branch for this issue to make testing it simpler. I should note that the 0.3 vs 15.1 comparison was on my laptop, when tested on my (pretty fast) desktop, it was 0.2 vs 3.5. So still slower, but not as bad as it was on the laptop.

**Instructions:**

1. `git clone git@github.com:FLIF-hub/node-flif.git`
1. `cd node-flif`
1. `git pull`
1. `git checkout wasm-test`
1. `npm install`
1. `npm run test-wasm`
1. `npm run test-exe`

**Note:** The `npm run test-exe` can only run on Windows since it is a native 32-bit win32 executable.

**Comment by saschanaz** [comment]
`v8.deserialize` to cache compiled WASM seems currently bugged. https://github.com/nodejs/node/issues/18265
